package bulkprocessor

import (
	"context"
	"encoding/json"
	"fmt"
	"log"
	"math/rand"
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"sync"
	"sync/atomic"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
	"github.com/lib/pq"
	"github.com/pkg/errors"
)

// BulkProcessor represents a bulk processor for PostgreSQL
type BulkProcessor struct {
	config            Config
	processId         string // Unique ID for this processor instance
	pgClient          *PostgreSQLClient
	s3Client          *S3Client
	fileManager       *FileManager
	structType        reflect.Type
	fields            []FieldInfo
	importerWg        sync.WaitGroup
	mutex             sync.RWMutex
	ctx               context.Context
	cancel            context.CancelFunc
	isStarted         bool
	flushMutex        sync.RWMutex
	isShutdown        bool
	fileQueue         chan string    // Queue of file IDs to be imported
	batchQueue        chan string    // Queue of batch directories to be imported
	routingQueue      chan bool      // channel to notify the routing table is updated
	routingQueueV2    chan bool      // channel to notify the routing table is updated
	pendingBatchFiles map[string]int // Map of batch directory to count of pending files
	pendingBatchMutex sync.RWMutex

	recordsQueue chan []string // Channel to write records, support one processor used by multiple goroutines
	recordsNum   int32         // Number of records in the recordsQueue
	// this hashmap used to store the column value, return the values to the upper layer
	// when import failed.
	// init: new processor, initialize the map.
	// write: for every insert record, write the specific column value into the map if
	// the value does not existed in the map.
	// read: when import failed, scan the map to get all the column values.
	// clear: finish the import, clear the map.
	feedbackKeys        map[string]bool
	feedbackKeysMutex   sync.RWMutex
	ImportErrorCallback ImportErrorHandler // Callback function to handle import errors
	feedFieldIndex      int
	lastFlushTime       time.Time
	hasRoutingTable     bool
	routingColIndex     int
	versionColIndex     int
	pkColumns           []string
	pkColumnsIndex      []int
	routingMutex        sync.RWMutex
	routingHashSet      map[string]struct{}

	bufferManager   *BufferManager
	bufferTaskQueue chan *BufferTask
	bufferThreadWg  sync.WaitGroup
	recordQueueV2   chan *Record

	// Global offset tracking using atomic variable
	maxOffset int64

	// parallel processing related fields
	workerWg          sync.WaitGroup
	activeWorkers     int32 // atomic counter for active workers
	routingTableCache map[string]struct {
		lastCheckTime   time.Time
		hasRoutingTable bool
	}
	routingTableCacheMutex sync.RWMutex
}

// SearchResult
type SearchResult struct {
	Columns []string        // column names
	Rows    [][]interface{} // data rows
}

// SearchOptions
type SearchOptions struct {
	Table     string   // table name
	Columns   []string // column names, if empty, select all columns. support alias, like "vector <-> $1 as ds"
	Condition string   // query condition, like "id = $1 AND name = $2"
	OrderBy   string   // order by, like "id DESC, name ASC"
	Limit     int      // limit, 0 means no limit
	Offset    int      // offset, for pagination
	GroupBy   string   // group by, like "id, name"
	Having    string   // having, like "id > 100"
	FinalSQL  string   // final sql, generated by the library with the other fields, do not need to set this field
}

// New creates a new BulkProcessor instance
func New(config Config) (*BulkProcessor, error) {
	// Validate config
	if err := config.Validate(); err != nil {
		return nil, err
	}

	SetLogLevel(config.LogLevel)

	// Generate a unique process ID
	processId := uuid.New().String()

	// Create PostgreSQL client first, as we need it to get S3 config
	pgClient, err := NewPostgreSQLClient(config.PostgreSQL)
	if err != nil {
		return nil, err
	}

	// Get S3 config from database
	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()

	// Get S3 config from database
	s3Config, err := pgClient.GetLoadConfigFromDB(ctx, &config)
	if err != nil {
		pgClient.Close()
		return nil, errors.Wrap(err, "failed to get S3 configuration from database")
	}

	// Create S3 client with the appropriate config
	s3Client, err := NewS3Client(*s3Config)
	if err != nil {
		// Make sure to close the PostgreSQL client if S3 client creation fails
		pgClient.Close()
		return nil, err
	}

	// Create file manager
	filePrefix := fmt.Sprintf("relyt_bulk_%s", strings.ReplaceAll(config.PostgreSQL.Table, ".", "_"))
	fileManager := NewFileManager(s3Client, filePrefix, config.BatchSize, processId, config.BatchImportSize)

	// Initialize checkpoint for this process
	pgTable := fmt.Sprintf("%s.%s", config.PostgreSQL.Schema, config.PostgreSQL.Table)
	if err := pgClient.InitializeCheckpoint(ctx, processId, pgTable); err != nil {
		pgClient.Close()
		return nil, errors.Wrap(err, "failed to initialize checkpoint")
	}

	routingTableName := fmt.Sprintf("%s%s", config.PostgreSQL.Table, routingTableSuffix)
	hasRoutingTable, err := pgClient.HasRoutingTable(ctx, routingTableName)
	if err != nil {
		pgClient.Close()
		return nil, errors.Wrap(err, "failed to check if routing table exists")
	}

	// Initialize routing table for this process
	routingHashSet := make(map[string]struct{})
	if hasRoutingTable {
		routingHashSet, err = pgClient.RefreshRoutingTable(ctx, routingTableName)
		Log("Init: routingHashSet size: %d", len(routingHashSet))
		if err != nil {
			pgClient.Close()
			return nil, errors.Wrap(err, "failed to initialize routing table")
		}
	}

	pkColumns, err := pgClient.GetTablePrimaryKeys(ctx)
	if err != nil {
		pgClient.Close()
		return nil, errors.Wrap(err, "failed to get primary keys")
	}

	var bufferManager *BufferManager
	if config.EnableDualBuffer {
		bufferManager = NewBufferManager(filePrefix, processId)
	}

	ctx, cancel = context.WithCancel(context.Background())

	return &BulkProcessor{
		config:            config,
		processId:         processId,
		pgClient:          pgClient,
		s3Client:          s3Client,
		fileManager:       fileManager,
		ctx:               ctx,
		cancel:            cancel,
		fileQueue:         make(chan string, 1000), // Buffer for file queue
		batchQueue:        make(chan string, 1000), // Buffer for batch queue
		routingQueue:      make(chan bool, 10),     // Buffer for routing table updated
		routingQueueV2:    make(chan bool, 10),     // Buffer for routing table updated
		pendingBatchFiles: make(map[string]int),    // Tracks files pending in each batch
		feedbackKeys:      make(map[string]bool),   // Tracks error keys for failed imports
		recordsQueue:      make(chan []string, 10000),
		feedFieldIndex:    -1,
		lastFlushTime:     time.Now(),
		hasRoutingTable:   hasRoutingTable,
		routingColIndex:   -1,
		versionColIndex:   -1,
		routingHashSet:    routingHashSet,
		pkColumns:         pkColumns,
		pkColumnsIndex:    nil,
		bufferManager:     bufferManager,
		bufferTaskQueue:   make(chan *BufferTask, 200),
		bufferThreadWg:    sync.WaitGroup{},
		recordQueueV2:     make(chan *Record, 10000),
		workerWg:          sync.WaitGroup{},
		activeWorkers:     0,
		routingTableCache: make(map[string]struct {
			lastCheckTime   time.Time
			hasRoutingTable bool
		}),
		routingTableCacheMutex: sync.RWMutex{},
	}, nil
}

// GetProcessId returns the unique processor ID
func (p *BulkProcessor) GetProcessId() string {
	return p.processId
}

func (p *BulkProcessor) GetRoutingTableName() string {
	return fmt.Sprintf("%s%s", p.config.PostgreSQL.Table, routingTableSuffix)
}

func (p *BulkProcessor) GetRoutingChannelName() string {
	return fmt.Sprintf("%s_channel", p.GetRoutingTableName())
}

func (p *BulkProcessor) GetAuxTableName() string {
	return fmt.Sprintf("%s%s", p.config.PostgreSQL.Table, auxTableSuffix)
}

// GetMaxOffset returns the global maximum offset
func (p *BulkProcessor) GetMaxOffset() int64 {
	return atomic.LoadInt64(&p.maxOffset)
}

// UpdateMaxOffset updates the global maximum offset if the new offset is greater
func (p *BulkProcessor) UpdateMaxOffset(newOffset int64) {
	for {
		current := atomic.LoadInt64(&p.maxOffset)
		if newOffset <= current {
			break
		}
		if atomic.CompareAndSwapInt64(&p.maxOffset, current, newOffset) {
			break
		}
	}
}

// Start starts the importer thread
func (p *BulkProcessor) Start() error {
	p.mutex.Lock()
	defer p.mutex.Unlock()

	if p.isStarted {
		return errors.New("bulk processor already started")
	}

	p.isStarted = true

	if p.config.PostgreSQL.Table == "" {
		Log("BulkProcessor Start: PostgreSQL table is empty, skip start background threads")
		return nil
	}

	if p.hasRoutingTable {
		p.importerWg.Add(1)
		go p.ListenThread()
	}

	p.importerWg.Add(1)
	go p.InsertThread()

	p.importerWg.Add(1)
	go p.ImporterThread()

	p.importerWg.Add(1)
	go p.AutoFlushThread()

	p.importerWg.Add(1)
	go p.BGWorkerThread()

	if p.config.EnableDualBuffer {

		p.bufferThreadWg.Add(1)
		go p.InsertThreadV2()

		p.bufferThreadWg.Add(1)
		go p.ImporterThreadV2()
	}

	return nil
}

// Shutdown shuts down the processor
func (p *BulkProcessor) Shutdown() error {
	p.mutex.Lock()
	defer p.mutex.Unlock()

	if p.isShutdown {
		return nil
	}

	p.isShutdown = true
	p.cancel()

	// Wait for importer to finish
	p.importerWg.Wait()

	// Wait for buffer threads to finish (if dual buffer is enabled)
	if p.config.EnableDualBuffer {
		p.bufferThreadWg.Wait()
		// wait for all parallel workers to finish
		p.workerWg.Wait()
	}

	// Create a list of all files that need to be cleaned up from S3
	allFiles := append(
		p.fileManager.GetFilesByState(FileStateFrozen),
		append(
			p.fileManager.GetFilesByState(FileStateImporting),
			p.fileManager.GetFilesByState(FileStateImported)...,
		)...,
	)

	// Cleanup files from local filesystem
	for _, file := range allFiles {
		if err := file.CleanupFile(); err != nil {
			fmt.Fprintf(os.Stderr, "Failed to cleanup local file: %v\n", err)
		}
	}

	// Cleanup S3 files
	// First gather all S3 keys that need to be deleted
	var s3Keys []string
	var normalFilepaths []string
	for _, file := range allFiles {
		if file.S3Key != "" && file.State != FileStateError && false {
			s3Keys = append(s3Keys, file.S3Key)
			normalFilepaths = append(normalFilepaths, file.S3Key)
		}
	}

	// Delete files from S3 if there are any
	if len(s3Keys) > 0 {
		ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
		if err := p.s3Client.DeleteObjects(ctx, s3Keys); err != nil {
			fmt.Fprintf(os.Stderr, "Failed to delete S3 objects during shutdown: %v\n", err)
		}
		cancel()
	}

	// Cleanup buffer files
	normalFilepaths = append(normalFilepaths, p.bufferManager.RecycleBuffers()...)

	// Cleanup checkpoint records
	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	if err := p.pgClient.DeleteDeltaCheckpointByProcessIdAndFilepaths(ctx, p.processId, normalFilepaths); err != nil {
		fmt.Fprintf(os.Stderr, "Failed to delete checkpoint records during shutdown: %v\n", err)
	}
	cancel()

	// Close clients
	p.pgClient.Close()

	return nil
}

// checkErrorCount checks if the current error can be ignored based on max error limit
// returns true if the error should be ignored, false if the error should be returned
func (p *BulkProcessor) checkErrorCount(err error, errorRecordsCount *int, recordIndex int, errorContext string) bool {
	if p.config.MaxErrorRecords <= 0 {
		return false
	}

	// Check if we've reached the max error limit
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	currentErrorCount, getErr := p.pgClient.GetCheckpointErrorRecords(ctx, p.processId)
	cancel()

	if getErr != nil {
		fmt.Fprintf(os.Stderr, "Failed to get current error count: %v\n", getErr)
		return false
	}

	if currentErrorCount+*errorRecordsCount+1 <= p.config.MaxErrorRecords {
		// This error is within our acceptable limit
		*errorRecordsCount++
		fmt.Fprintf(os.Stderr, "Ignoring error %s record %d: %v (total errors: %d/%d)\n",
			errorContext, recordIndex, err, currentErrorCount+*errorRecordsCount, p.config.MaxErrorRecords)
		return true
	}

	return false
}

// Insert inserts data into the processor
func (p *BulkProcessor) Insert(data interface{}) error {

	if p.config.PostgreSQL.Table == "" {
		return ErrPostgreSQLTableRequired
	}

	p.mutex.RLock()
	if p.isShutdown {
		p.mutex.RUnlock()
		return ErrProcessorClosed
	}
	p.mutex.RUnlock()

	// Start processor if not started
	if !p.isStarted {
		if err := p.Start(); err != nil {
			return err
		}
	}

	// Check if data is a slice
	val := reflect.ValueOf(data)
	if val.Kind() == reflect.Ptr {
		val = val.Elem()
	}

	if val.Kind() != reflect.Slice {
		return ErrInvalidInput
	}

	if val.Len() == 0 {
		return ErrEmptyInput
	}

	// Get the struct type if not already set
	if p.structType == nil {
		elemType := val.Type().Elem()
		if elemType.Kind() == reflect.Ptr {
			elemType = elemType.Elem()
		}

		if elemType.Kind() != reflect.Struct {
			return errors.New("input must be a slice of structs")
		}

		fields, err := GetStructFields(elemType)
		if err != nil {
			return err
		}

		if len(fields) == 0 {
			return errors.New("no valid fields found in struct")
		}

		p.structType = elemType
		p.fields = fields
	}

	// To track error records in this batch
	errorRecordsCount := 0

	// Process each record
	for i := 0; i < val.Len(); i++ {
		elemVal := val.Index(i)
		if elemVal.Kind() == reflect.Ptr {
			if elemVal.IsNil() {
				continue
			}
			elemVal = elemVal.Elem()
		}

		// Get field values
		values, err := GetFieldValues(elemVal.Interface(), p.fields)
		if err != nil {
			if p.checkErrorCount(err, &errorRecordsCount, i, "in") {
				continue // Skip this record and continue
			}

			// Either too many errors or couldn't get error count
			return err
		}

		if p.feedFieldIndex < 0 {
			p.feedFieldIndex = GetColumnIndex(p.fields, p.config.FeedbackColumn)
		}

		if p.routingColIndex < 0 {
			p.routingColIndex = GetColumnIndex(p.fields, "routing_id")
		}

		p.recordsQueue <- values
		atomic.AddInt32(&p.recordsNum, 1)
	}

	return nil
}

// consume records from the recordsQueue and process them
func (p *BulkProcessor) InsertThread() error {
	defer p.importerWg.Done()

	var localRoutingInited = false
	var localRoutingHashSet map[string]struct{}

	for {
		select {
		case <-p.ctx.Done():
			log.Println("Insert thread context canceled, exiting...")
			return nil
		case <-p.routingQueue:
			p.routingMutex.Lock()
			localRoutingHashSet = p.routingHashSet
			localRoutingInited = true
			p.routingMutex.Unlock()
		case values := <-p.recordsQueue:
			if p.feedFieldIndex >= 0 {
				index := p.feedFieldIndex
				p.feedbackKeysMutex.Lock()
				// Check if feedback column value already exists in the map
				if _, exists := p.feedbackKeys[values[index]]; !exists {
					// Add the feedback column value to the map
					p.feedbackKeys[values[index]] = true
				} else {
					// If it already exists, we can skip adding it again
					log.Printf("Feedback key already exists: %s", values[index])
				}
				p.feedbackKeysMutex.Unlock()
			}

			toAuxFile := false
			if p.routingColIndex >= 0 {
				if !localRoutingInited {
					p.routingMutex.Lock()
					localRoutingHashSet = p.routingHashSet
					localRoutingInited = true
					p.routingMutex.Unlock()
					log.Printf("Init localRoutingHashSet, size is: %d", len(localRoutingHashSet))
				}
				if _, exists := localRoutingHashSet[values[p.routingColIndex]]; exists {
					toAuxFile = true
				}
			}

			p.fileManager.fileOperationsMutex.Lock()

			currentFile := p.fileManager.GetCurrentFile(toAuxFile)
			if currentFile == nil || currentFile.State != FileStateOpen {
				log.Printf("InsertThread Current file is nil or not open, creating a new file, toAuxFile: %v", toAuxFile)
				// Create a new file
				columnNames := GetColumnNames(p.fields)
				var err error
				currentFile, err = p.fileManager.CreateFile(columnNames, toAuxFile)
				if err != nil {
					feedbackKeysArray := p.getFeedbackValues()
					if p.config.ImportErrorCallback != nil {
						p.config.ImportErrorCallback(p.config.FeedbackColumn, feedbackKeysArray, err, p.config.CallbackResource)
					} else {
						feedbackKeysString := fmt.Sprintf("failed %s is [%s].", p.config.FeedbackColumn, strings.Join(feedbackKeysArray, ","))
						log.Printf("Batch import failed with no callback: %s", feedbackKeysString)
					}
					p.fileManager.fileOperationsMutex.Unlock()
					continue
				}
				p.fileManager.SetCurrentFile(currentFile, toAuxFile)
				log.Printf("InsertThread Current file created: %s", currentFile.S3Key)

				// Update checkpoint with new file
				ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
				defer cancel()

				targetTable := p.config.PostgreSQL.Table
				if toAuxFile {
					targetTable = p.GetAuxTableName()
				}
				pgTable := fmt.Sprintf("%s.%s", p.config.PostgreSQL.Schema, targetTable)

				if err := p.pgClient.InsertDeltaCheckpoint(ctx, p.processId, pgTable, currentFile.S3Key); err != nil {
					Debug("Failed to insert delta checkpoint with new file: %s, %v", currentFile.S3Key, err)
				}
			}
			//log.Printf("InsertThread Current file state: %v, num records: %d", currentFile.State, currentFile.NumRecords)
			// Write record to file
			err := currentFile.WriteRecord(values)
			if err != nil {
				feedbackKeysArray := p.getFeedbackValues()
				if p.config.ImportErrorCallback != nil {
					p.config.ImportErrorCallback(p.config.FeedbackColumn, feedbackKeysArray, err, p.config.CallbackResource)
				} else {
					feedbackKeysString := fmt.Sprintf("failed %s is [%s].", p.config.FeedbackColumn, strings.Join(feedbackKeysArray, ","))
					log.Printf("Batch import failed with no callback: %s", feedbackKeysString)
				}
				p.fileManager.fileOperationsMutex.Unlock()
				continue
			}

			// Check if file is full
			if currentFile.IsFull(p.config.BatchSize) {
				// Flush and close the file
				if err := currentFile.Flush(); err != nil {
					feedbackKeysArray := p.getFeedbackValues()
					if p.config.ImportErrorCallback != nil {
						p.config.ImportErrorCallback(p.config.FeedbackColumn, feedbackKeysArray, err, p.config.CallbackResource)
					} else {
						feedbackKeysString := fmt.Sprintf("failed %s is [%s].", p.config.FeedbackColumn, strings.Join(feedbackKeysArray, ","))
						log.Printf("Batch import failed with no callback: %s", feedbackKeysString)
					}
					p.fileManager.fileOperationsMutex.Unlock()
					continue
				}

				// Close the file to finalize the S3 upload
				if err := currentFile.Close(); err != nil {
					feedbackKeysArray := p.getFeedbackValues()
					if p.config.ImportErrorCallback != nil {
						p.config.ImportErrorCallback(p.config.FeedbackColumn, feedbackKeysArray, err, p.config.CallbackResource)
					} else {
						feedbackKeysString := fmt.Sprintf("failed %s is [%s].", p.config.FeedbackColumn, strings.Join(feedbackKeysArray, ","))
						log.Printf("Batch import failed with no callback: %s", feedbackKeysString)
					}
					p.fileManager.fileOperationsMutex.Unlock()
					continue
				}

				p.fileManager.fileOperationsMutex.Unlock()

				// Set S3 URL
				currentFile.S3URL = p.s3Client.GetS3URL(currentFile.S3Key)

				// Update file state to frozen
				p.fileManager.UpdateFileState(currentFile.ID, FileStateFrozen)

				if err := p.AddFileToPendingBatchFiles(currentFile); err != nil {
					feedbackKeysArray := p.getFeedbackValues()
					if p.config.ImportErrorCallback != nil {
						p.config.ImportErrorCallback(p.config.FeedbackColumn, feedbackKeysArray, err, p.config.CallbackResource)
					} else {
						feedbackKeysString := fmt.Sprintf("failed %s is [%s].", p.config.FeedbackColumn, strings.Join(feedbackKeysArray, ","))
						log.Printf("Batch import failed with no callback: %s", feedbackKeysString)
					}
					p.fileManager.fileOperationsMutex.Unlock()
					continue
				}
			} else {
				p.fileManager.fileOperationsMutex.Unlock()
			}
			atomic.AddInt32(&p.recordsNum, -1)
		}
	}
}

// Flush flushes all pending data and waits for import to complete
func (p *BulkProcessor) Flush() error {
	p.mutex.Lock()
	if p.isShutdown {
		p.mutex.Unlock()
		return ErrProcessorClosed
	}
	p.mutex.Unlock()

	p.flushMutex.Lock()
	defer p.flushMutex.Unlock()

	// check recordsNum
	for {
		if atomic.LoadInt32(&p.recordsNum) == 0 {
			break
		}
		Debug("Flush wait for recordsNum to be 0, current recordsNum: %d", atomic.LoadInt32(&p.recordsNum))
		time.Sleep(time.Duration(1) * time.Second)
	}

	needFlushBufferIds := []string{}

	// flush buffer
	if p.config.EnableDualBuffer {
		for _, isAux := range []bool{false, true} {
			p.bufferManager.bufferOperationsMutex.Lock()
			currentBuffer := p.bufferManager.GetCurrentBuffer(isAux)
			if currentBuffer != nil && currentBuffer.GetRecordCount() > 0 && p.bufferManager.IsActive(currentBuffer.ID) {
				// deactivate current buffer, create new buffer
				p.bufferManager.SetBufferStatus(currentBuffer.ID, BufferStatusFrozen)
				p.bufferManager.SetCurrentBuffer(nil, isAux)
				p.bufferManager.bufferOperationsMutex.Unlock()

				if err := p.SaveBufferToFileAndGenerateTask(currentBuffer, isAux); err != nil {
					p.bufferManager.SetBufferStatus(currentBuffer.ID, BufferStatusFlushError)
					feedbackKeysArray := p.getFeedbackValues()
					feedbackKeysString := fmt.Sprintf("failed %s is [%s].", p.config.FeedbackColumn, strings.Join(feedbackKeysArray, ","))

					if p.config.ImportErrorCallback != nil {
						Warning("save file: %s failed before callback: %s", currentBuffer.ID, feedbackKeysString)
						p.config.ImportErrorCallback(p.config.FeedbackColumn, feedbackKeysArray, err, p.config.CallbackResource)
					} else {
						Warning("save file: %s failed with no callback: %s", currentBuffer.ID, feedbackKeysString)
					}
					continue
				}
				p.bufferManager.SetBufferStatus(currentBuffer.ID, BufferStatusFlushed)
			} else {
				p.bufferManager.bufferOperationsMutex.Unlock()
			}
		}

		buffers := p.bufferManager.GetBufferByStatus(BufferStatusFlushed, BufferStatusFrozen)
		for _, buffer := range buffers {
			needFlushBufferIds = append(needFlushBufferIds, buffer.ID)
		}
	}

	p.fileManager.fileOperationsMutex.Lock()
	for _, isAux := range []bool{false, true} {
		// Flush current file if it has records
		currentFile := p.fileManager.GetCurrentFile(isAux)
		if currentFile != nil && currentFile.State == FileStateOpen && currentFile.NumRecords > 0 {
			Debug("Flushing current file: %s", currentFile.S3Key)
			if err := currentFile.Flush(); err != nil {
				p.fileManager.fileOperationsMutex.Unlock()
				return err
			}

			// Close the file to finalize the S3 upload
			if err := currentFile.Close(); err != nil {
				p.fileManager.fileOperationsMutex.Unlock()
				return err
			}

			// Set S3 URL
			currentFile.S3URL = p.s3Client.GetS3URL(currentFile.S3Key)

			// Update file state to frozen
			p.fileManager.UpdateFileState(currentFile.ID, FileStateFrozen)

			if err := p.AddFileToPendingBatchFiles(currentFile); err != nil {
				p.fileManager.fileOperationsMutex.Unlock()
				return err
			}

			// next CreateFile will reset the batchCounter
			currentFileInfo := p.fileManager.GetCurrentFileInfo(isAux)
			currentFileInfo.batchCounter = p.config.BatchImportSize
		}
	}

	batchDir := ""
	sendDirectory := false

	// flush all pendingBatchFiles
	p.pendingBatchMutex.Lock()
	for dir, count := range p.pendingBatchFiles {
		if count > 0 {
			sendDirectory = true
			Debug("Queuing batch directory for import: %s with %d files", dir, count)
			batchDir = dir
			p.batchQueue <- dir
		}
		delete(p.pendingBatchFiles, dir)
	}
	p.lastFlushTime = time.Now()
	p.pendingBatchMutex.Unlock()

	p.fileManager.fileOperationsMutex.Unlock()

	// if no directory send to import, return ASAP
	if !sendDirectory && len(needFlushBufferIds) == 0 {
		Debug("flush without any data")
		return nil
	}

	// Wait for all files to be imported or an error to occur
	for {
		// Check for context cancellation
		select {
		case <-p.ctx.Done():
			// Context canceled, might be a shutdown
			// Only report it as an error if we're not in shutdown
			p.mutex.RLock()
			isShutdown := p.isShutdown
			p.mutex.RUnlock()

			if !isShutdown {
				return errors.New("import process canceled")
			}
			// If in shutdown mode, continue to check files
		default:
			// Not canceled
		}

		// Check if all files are imported under the given directory
		frozenFiles := p.fileManager.GetFilesByStateAndDirectory(FileStateFrozen, batchDir)
		importingFiles := p.fileManager.GetFilesByStateAndDirectory(FileStateImporting, batchDir)
		errorFiles := p.fileManager.GetFilesByStateAndDirectory(FileStateError, batchDir)

		flushingBuffers := []*Buffer{}
		errorBuffers := []*Buffer{}

		for _, bufferId := range needFlushBufferIds {
			buffer := p.bufferManager.GetBufferByID(bufferId)
			if buffer != nil {
				if buffer.status == BufferStatusFlushError || buffer.status == BufferStatusImportError {
					errorBuffers = append(errorBuffers, buffer)
				} else if buffer.status == BufferStatusFrozen || buffer.status == BufferStatusFlushed {
					flushingBuffers = append(flushingBuffers, buffer)
				}
			}
		}

		if len(errorFiles)+len(errorBuffers) > 0 {
			// sleep at least 100ms because there are two updates to checkpoint
			sleepTime := p.config.FlushSleepTime
			if sleepTime <= 1000 {
				sleepTime = 1000
			}
			time.Sleep(time.Duration(sleepTime) * time.Millisecond)

			return errors.New("import failed, check delta checkpoint for more details")
		}

		// If no files are pending, we're done
		if len(frozenFiles) == 0 && len(importingFiles) == 0 && len(flushingBuffers) == 0 {
			Debug("No files to import, exiting...")
			return nil
		}

		// Short sleep to avoid excessive CPU usage
		time.Sleep(time.Duration(p.config.FlushSleepTime) * time.Millisecond)
	}
}

// importerThread processes files from the queue
func (p *BulkProcessor) ImporterThread() {
	defer p.importerWg.Done()

	for {
		select {
		case <-p.ctx.Done():
			log.Println("Importer thread context canceled, exiting...")
			return

		case batchDir := <-p.batchQueue:
			log.Printf("Geting batch directory for import: %s", batchDir)
			// Process a whole batch directory
			if batchDir == "" {
				continue
			}

			// Get all files in this batch directory
			files := p.fileManager.GetFilesByBatchDirectory(batchDir)
			if len(files) == 0 {
				continue
			}

			feedbackKeysArray := p.getFeedbackValues()

			// Update state of all files to importing
			for _, file := range files {
				// Skip if not in frozen state
				if file.State != FileStateFrozen {
					continue
				}
				// Update state to importing
				p.fileManager.UpdateFileState(file.ID, FileStateImporting)
			}

			isAuxFile := strings.Contains(batchDir, BatchPrefixAux)
			// Import the entire batch directory
			isFailed := true
			maxLoopNum := p.config.ImportTimeout / p.config.ImportErrorSleepTime
			err := errors.New("import batch directory timeout")
			for i := 0; i < maxLoopNum; i++ {
				err = p.importBatchDirectory(batchDir, isAuxFile)
				if err != nil {
					var filepaths []string
					for _, file := range files {
						filepaths = append(filepaths, file.S3Key)
					}

					// Update checkpoint with all error file
					ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
					if err2 := p.pgClient.UpdateDeltaCheckpointStatus(ctx, p.processId, filepaths, CheckpointStatusFailed, -1, err.Error()); err2 != nil {
						fmt.Fprintf(os.Stderr, "Failed to update checkpoint for error file: %v\n", err2)
					}
					cancel()

					// all the errors without parsing error are not expected, we will retry, parsing error just call
					// the callback and continue to next batch
					if !strings.Contains(err.Error(), "Bad literal") && !strings.Contains(err.Error(), "Dimensions") {
						time.Sleep(time.Duration(p.config.ImportErrorSleepTime) * time.Second)
						continue
					}

					// Mark all files as error
					for _, file := range files {
						file.SetError(fmt.Sprintf("failed to load batch: %v", err))
					}

					feedbackKeysString := fmt.Sprintf("failed %s is [%s].", p.config.FeedbackColumn, strings.Join(feedbackKeysArray, ","))

					if p.config.ImportErrorCallback != nil {
						log.Printf("Batch import failed before callback: %s", feedbackKeysString)
						p.config.ImportErrorCallback(p.config.FeedbackColumn, feedbackKeysArray, err, p.config.CallbackResource)
					} else {
						log.Printf("Batch import failed with no callback: %s", feedbackKeysString)
					}

					// continue to next batch, it is more reasonable to continue processing if upper-level
					// does not exit in the callback.
					isFailed = true
					break
				} else {
					isFailed = false
					break
				}
			}

			if isFailed {
				feedbackKeysString := fmt.Sprintf("failed %s is [%s].", p.config.FeedbackColumn, strings.Join(feedbackKeysArray, ","))
				log.Printf("Import batch directory timeout: %s", feedbackKeysString)
				if p.config.ImportErrorCallback != nil {
					p.config.ImportErrorCallback(p.config.FeedbackColumn, feedbackKeysArray, err, p.config.CallbackResource)
				}
				continue
			}

			// Update all files to imported state
			var filepaths []string
			for _, file := range files {
				// Update state to imported and record import time
				file.ImportedAt = time.Now()
				log.Printf("File imported: %s", file.S3Key)

				p.fileManager.UpdateFileState(file.ID, FileStateImported)

				// Cleanup file
				if err := file.CleanupFile(); err != nil {
					fmt.Fprintf(os.Stderr, "Failed to cleanup file: %v\n", err)
				}
				filepaths = append(filepaths, file.S3Key)
			}

			// Update checkpoint with all imported file
			ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
			if err := p.pgClient.UpdateDeltaCheckpointStatus(ctx, p.processId, filepaths, CheckpointStatusCompleted, 0, ""); err != nil {
				fmt.Fprintf(os.Stderr, "Failed to update checkpoint for imported file: %v\n", err)
			}
			cancel()
		}
	}
}

// importBatchDirectory imports all files in a batch directory with a single operation
func (p *BulkProcessor) importBatchDirectory(batchDir string, isAuxFile bool) error {
	ctx, cancel := context.WithTimeout(p.ctx, 60*time.Minute) // Longer timeout for batch imports
	defer cancel()

	// Get S3 directory path
	datePath := time.Now().Format("2006-01-02")
	dirPath := filepath.Join(datePath, p.processId, batchDir)

	// Get S3 directory URL
	dirURL := p.s3Client.GetS3DirURL(dirPath)

	// Generate a unique table name for the external table
	externalTableName := fmt.Sprintf("ext_%s_%s",
		strings.ReplaceAll(p.config.PostgreSQL.Table, ".", "_"),
		batchDir)

	// Get column names from fields
	columnNames := GetColumnNames(p.fields)

	// Get fresh S3 config from database for the import
	s3Config, err := p.pgClient.GetLoadConfigFromDB(ctx, &p.config)
	if err != nil {
		return errors.Wrap(err, "failed to get loader configuration from database for batch import")
	}
	// Create external table with column names (types will be taken from target table)
	// Note: Using directory URL instead of single file URL
	// Drop external table, becuase we have a retry mechanism in the import process
	err = p.pgClient.DropExternalTable(ctx, externalTableName)
	if err != nil {
		return err
	}

	err = p.pgClient.CreateExternalTable(ctx, dirURL, externalTableName, columnNames, *s3Config)
	if err != nil {
		return err
	}

	// Import data from external table
	err = p.pgClient.ImportFromExternalTable(ctx, externalTableName, columnNames, p.config.UpdateOnConflict, isAuxFile)
	if err != nil {
		return err
	}

	// Drop external table
	err = p.pgClient.DropExternalTable(ctx, externalTableName)
	if err != nil {
		return err
	}

	return nil
}

func (p *BulkProcessor) AutoFlushThread() {
	defer p.importerWg.Done()

	for {
		select {
		case <-p.ctx.Done():
			log.Println("AutoFlush thread context canceled, exiting...")
			return
		default:
			// Not canceled
		}
		fileTimeoutDuration := time.Duration(p.config.FileWriteTimeout) * time.Second
		if time.Since(p.lastFlushTime) >= fileTimeoutDuration {
			Debug("AutoFlush thread doing flush (last flush: %v)", p.lastFlushTime)
			p.Flush()
		} else {
			timeSleep := fileTimeoutDuration - time.Since(p.lastFlushTime)
			Debug("AutoFlush thread waiting for autoflush (last flush: %v)", p.lastFlushTime)
			time.Sleep(time.Duration(timeSleep))
		}
	}
}

func (p *BulkProcessor) BGWorkerThread() {
	defer p.importerWg.Done()

	for {
		select {
		case <-p.ctx.Done():
			log.Println("BGWorker thread context canceled, exiting...")
			return
		default:
			// Not canceled
		}

		// 1. recycle files and buffers. only recycle local files, not s3 files,
		//	- S3 files can be set to automatically clean up.
		//	- Back up local data to prevent data loss caused by local file loss.
		importedFilepaths := p.fileManager.RecycleFiles(false)
		importedFilepaths = append(importedFilepaths, p.bufferManager.RecycleBuffers()...)
		if len(importedFilepaths) > 0 {
			Log("BGWORKER: recycling files, file number: %d", len(importedFilepaths))
			ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
			if err := p.pgClient.DeleteDeltaCheckpointByProcessIdAndFilepaths(ctx, p.processId, importedFilepaths); err != nil {
				Debug("Failed to delete delta checkpoint for recycled file: %v\n", err)
			}
			// delete completed delta checkpoint 24 hours ago
			err := p.pgClient.DeleteCompletedDeltaCheckpoint(ctx, 24)
			if err != nil {
				Debug("Failed to delete completed delta checkpoint: %v", err)
			}
			cancel()
		}

		// 2. update load config
		ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
		err := p.pgClient.UpdateLoadConfig(ctx, &p.config)
		if err != nil {
			Debug("Failed to update load config: %v", err)
			time.Sleep(1 * time.Second)
		}
		cancel()

		// 3. check if the local csv directory files
		dirPath := p.bufferManager.GetLocalCSVDir()
		fullPath := filepath.Join(p.config.LocalFilePrefix, dirPath)
		if _, err := os.Stat(fullPath); os.IsNotExist(err) {
			Debug("BGWORKER: Directory %s does not exist, skipping", fullPath)
		} else {
			files, err := os.ReadDir(fullPath)
			if err != nil {
				Error("Failed to read directory: %v", err)
			} else {
				Log("BGWORKER: Found %d files in %s", len(files), fullPath)
			}
		}

		// 4. recycle local csv directory files, 2 days ago
		deletedPaths := p.bufferManager.RecycleLocalDir(p.config.LocalFilePrefix, 2)
		if len(deletedPaths) > 0 {
			Log("BGWORKER: Recycled %v old local directories", deletedPaths)
		}

		time.Sleep(time.Duration(p.config.BGWorkerInterval) * time.Second)
	}
}

func (p *BulkProcessor) getFeedbackValues() []string {
	// scan the feedbackKeys map to get all the column values
	// concate the column values with a comma and send it to the import error channel
	var feedbackKeysArray []string
	p.feedbackKeysMutex.Lock()
	for key := range p.feedbackKeys {
		feedbackKeysArray = append(feedbackKeysArray, key)
	}

	// clear the feedbackKeys map
	p.feedbackKeys = make(map[string]bool)
	p.feedbackKeysMutex.Unlock()

	return feedbackKeysArray
}

// add file to pendingBatchFiles
func (p *BulkProcessor) AddFileToPendingBatchFiles(file *File) error {
	// Skip if not in frozen state
	if file.State != FileStateFrozen {
		return errors.New("file is not in frozen state")
	}

	batchDir := file.BatchDir

	// Add to pending batch files
	p.pendingBatchMutex.Lock()
	p.pendingBatchFiles[batchDir]++
	pendingCount := p.pendingBatchFiles[batchDir]

	log.Printf("File %s added to pending batch directory %s, current count: %d", file.S3Key, batchDir, pendingCount)

	// If we have collected all files for this batch, queue the batch for import
	if pendingCount >= p.config.BatchImportSize {
		delete(p.pendingBatchFiles, batchDir) // Clear the counter
		log.Printf("Queuing batch directory for import: %s with %d files", batchDir, pendingCount)
		// Queue the batch for import
		p.batchQueue <- batchDir
		p.lastFlushTime = time.Now()
	}

	p.pendingBatchMutex.Unlock()
	return nil
}

func (p *BulkProcessor) ListenThread() {
	defer p.importerWg.Done()

	listenChannelName := fmt.Sprintf("LISTEN %s", p.GetRoutingChannelName())

	// Create trigger
	if err := p.pgClient.CreateRoutingTableTrigger(p.ctx, p.GetRoutingTableName(), p.GetRoutingChannelName()); err != nil {
		log.Printf("Failed to create trigger: %v", err)
		return
	}

	for {
		select {
		case <-p.ctx.Done():
			log.Println("Listener thread context canceled, exiting...")
			return
		default:
			conn, err := p.pgClient.pool.Acquire(p.ctx)
			if err != nil {
				Debug("Error acquiring connection: %v", err)
				time.Sleep(5 * time.Second)
				continue
			}

			// Start listening for notifications
			_, err = conn.Exec(p.ctx, listenChannelName)
			if err != nil {
				conn.Release()
				Debug("Error listening to routing table changes: %v", err)
				time.Sleep(5 * time.Second)
				continue
			}

			// Continuously listen for notifications
			for {
				select {
				case <-p.ctx.Done():
					conn.Release()
					Log("Listener thread context canceled, exiting...")
					return
				default:
					// Wait for notification
					_, err := conn.Conn().WaitForNotification(p.ctx)
					if err != nil {
						if err == context.Canceled {
							conn.Release()
							Log("Listener thread context canceled, exiting...")
							return
						}
						// Connection error, release current connection and break inner loop to reconnect
						Debug("Listener Connection error, will reconnect: %v", err)
						time.Sleep(1 * time.Second)
						conn.Release()
						goto reconnect
					}

					// Get updated routing table data after receiving notification
					newRoutingHashSet, err := p.pgClient.RefreshRoutingTable(p.ctx, p.GetRoutingTableName())
					if err != nil {
						Debug("Error getting updated routing table: %v", err)
						continue
					}

					// Update routing table using callback function
					p.routingMutex.Lock()
					oldsize := len(p.routingHashSet)
					newsize := len(newRoutingHashSet)
					p.routingHashSet = newRoutingHashSet
					p.routingMutex.Unlock()
					p.routingQueue <- true
					p.routingQueueV2 <- true
					Debug("Routing table updated, old size is: %d, new size is: %d, and exec force flush", oldsize, newsize)
					p.Flush()
				}
			}
		}
	reconnect:
		continue
	}
}

// InsertV2 insert data with dual buffer
func (p *BulkProcessor) InsertV2(fileID, routingID string, records interface{}, offset ...int64) error {
	if p.config.PostgreSQL.Table == "" {
		return ErrPostgreSQLTableRequired
	}

	if !p.config.EnableDualBuffer {
		return errors.New("dual buffer is not enabled")
	}

	p.mutex.RLock()
	if p.isShutdown {
		p.mutex.RUnlock()
		return ErrProcessorClosed
	}
	p.mutex.RUnlock()

	// start processor if not started
	if !p.isStarted {
		if err := p.Start(); err != nil {
			return err
		}
	}

	// check if data is a slice
	val := reflect.ValueOf(records)
	if val.Kind() == reflect.Ptr {
		val = val.Elem()
	}

	if val.Kind() != reflect.Slice {
		return ErrInvalidInput
	}

	if val.Len() == 0 {
		return ErrEmptyInput
	}

	// get struct type if not set
	if p.structType == nil {
		elemType := val.Type().Elem()
		if elemType.Kind() == reflect.Ptr {
			elemType = elemType.Elem()
		}

		if elemType.Kind() != reflect.Struct {
			return errors.New("input must be a slice of structs")
		}

		fields, err := GetStructFields(elemType)
		if err != nil {
			return err
		}

		if len(fields) == 0 {
			return errors.New("no valid fields found in struct")
		}

		p.structType = elemType
		p.fields = fields

		if p.routingColIndex < 0 {
			p.routingColIndex = GetColumnIndex(p.fields, "routing_id")
		}

		if p.versionColIndex < 0 {
			p.versionColIndex = GetColumnIndex(p.fields, "version")
		}

		if p.pkColumnsIndex == nil && len(p.pkColumns) > 0 {
			p.pkColumnsIndex = make([]int, len(p.pkColumns))
			for i, columnName := range p.pkColumns {
				p.pkColumnsIndex[i] = GetColumnIndex(p.fields, columnName)
			}
			Debug("pkColumnsIndex: %v", p.pkColumnsIndex)
		}
	}

	// Get offset value, default to 0 if not provided
	var recordOffset int64 = 0
	if len(offset) > 0 {
		recordOffset = offset[0]
	}

	// process each record and write to recordQueueV2
	for i := 0; i < val.Len(); i++ {
		elemVal := val.Index(i)
		if elemVal.Kind() == reflect.Ptr {
			if elemVal.IsNil() {
				continue
			}
			elemVal = elemVal.Elem()
		}

		// get field values
		values, err := GetFieldValues(elemVal.Interface(), p.fields)
		if err != nil {
			return err
		}

		if p.feedFieldIndex < 0 {
			p.feedFieldIndex = GetColumnIndex(p.fields, p.config.FeedbackColumn)
		}

		// create record and write to queue
		record := &Record{
			Tag:       OperationInsert,
			FileID:    fileID,
			RoutingID: routingID,
			Values:    values,
			Offset:    recordOffset,
		}

		p.recordQueueV2 <- record
		atomic.AddInt32(&p.recordsNum, 1)
	}

	return nil
}

func (p *BulkProcessor) DeleteSyncV2(fileID, routingID string) error {
	if p.config.PostgreSQL.Table == "" {
		return ErrPostgreSQLTableRequired
	}

	p.mutex.RLock()
	if p.isShutdown {
		p.mutex.RUnlock()
		return ErrProcessorClosed
	}
	p.mutex.RUnlock()

	// In order to solve DeleteSyncV2() failure in server (upgrade etc.),
	// an asynchronous deletion method is added here.The business side needs to ensure:
	// 1. No need to execute DeleteSyncV2() before insert, batch operation will automatically execute deletion.
	// 	Refer to processBufferTaskWithTransaction and guc:DeleteBeforeInsert, otherwise insert first and then delete may cause data loss
	// 2. DeleteSyncV2 will only be called when data is actually deleted. If synchronous deletion fails,
	// 	it will be converted to asynchronous, and the deletion will be successful after the database is restored.
	if p.config.AsyncDelete {
		return p.DeleteV2(fileID, routingID)
	}

	_, err := p.pgClient.DeleteTablesWithCondition(p.ctx, p.config.PostgreSQL.Schema, p.config.PostgreSQL.Table, fileID, routingID, p.hasRoutingTable)
	if err != nil {
		Debug("Failed to delete file %s with routingID %s sync: %v, will retry in async mode", fileID, routingID, err)
		return p.DeleteV2(fileID, routingID)
	}

	return nil
}

func (p *BulkProcessor) DeleteByGroupV2(groupID, routingID string) error {

	if p.config.PostgreSQL.Table == "" {
		return ErrPostgreSQLTableRequired
	}

	p.mutex.RLock()
	if p.isShutdown {
		p.mutex.RUnlock()
		return ErrProcessorClosed
	}
	p.mutex.RUnlock()

	if p.config.AsyncDelete {
		return p.DeleteAsyncGroupV2(groupID, routingID)
	}

	_, err := p.pgClient.DeleteTablesWithGroup(p.ctx, p.config.PostgreSQL.Schema, p.config.PostgreSQL.Table, groupID, routingID, p.hasRoutingTable)
	if err != nil {
		Debug("Failed to delete group %s with routingID %s sync: %v, will retry in async mode", groupID, routingID, err)
		return p.DeleteAsyncGroupV2(groupID, routingID)
	}

	return nil
}

func (p *BulkProcessor) DeleteAsyncGroupV2(groupID, routingID string, offset ...int64) error {
	if p.config.PostgreSQL.Table == "" {
		return ErrPostgreSQLTableRequired
	}

	if !p.config.EnableDualBuffer {
		return errors.New("dual buffer is not enabled")
	}

	p.mutex.RLock()
	if p.isShutdown {
		p.mutex.RUnlock()
		return ErrProcessorClosed
	}
	p.mutex.RUnlock()

	// start processor if not started
	if !p.isStarted {
		if err := p.Start(); err != nil {
			return err
		}
	}

	// Get offset value, default to 0 if not provided
	var recordOffset int64 = 0
	if len(offset) > 1 {
		return errors.New("offset must be a single value")
	} else if len(offset) == 1 {
		recordOffset = offset[0]
	}

	// create delete record and write to queue
	record := &Record{
		Tag:       OperationDelete,
		RoutingID: routingID,
		GroupID:   groupID,
		Values:    nil,
		Offset:    recordOffset,
	}

	p.recordQueueV2 <- record

	atomic.AddInt32(&p.recordsNum, 1)

	return nil
}

func (p *BulkProcessor) DeleteV2(fileID, routingID string, offset ...int64) error {

	if p.config.PostgreSQL.Table == "" {
		return ErrPostgreSQLTableRequired
	}

	if !p.config.EnableDualBuffer {
		return errors.New("dual buffer is not enabled")
	}

	p.mutex.RLock()
	if p.isShutdown {
		p.mutex.RUnlock()
		return ErrProcessorClosed
	}
	p.mutex.RUnlock()

	// start processor if not started
	if !p.isStarted {
		if err := p.Start(); err != nil {
			return err
		}
	}

	// Get offset value, default to 0 if not provided
	var recordOffset int64 = 0
	if len(offset) > 1 {
		return errors.New("offset must be a single value")
	} else if len(offset) == 1 {
		recordOffset = offset[0]
	}

	// create delete record and write to queue
	record := &Record{
		Tag:       OperationDelete,
		FileID:    fileID,
		RoutingID: routingID,
		Values:    nil,
		Offset:    recordOffset,
	}

	p.recordQueueV2 <- record

	atomic.AddInt32(&p.recordsNum, 1)

	return nil
}

func (p *BulkProcessor) SaveBufferToFileAndGenerateTask(currentBuffer *Buffer, toAuxFile bool) error {
	Debug("Buffer %s is full (records: %d), switching buffers",
		currentBuffer.ID, currentBuffer.GetRecordCount())

	// deduplicate records
	deletedRecords, deletedGroupRecords, versionMap := currentBuffer.DeduplicateRecords(len(p.pkColumns) > 0, p.versionColIndex >= 0, p.config.DeleteBeforeInsert)

	columnNames := GetColumnNames(p.fields)

	taskImportStrategy := p.config.ImportStrategy

	if err := currentBuffer.BufferWriteToFile(columnNames, p.s3Client, p.config.TuplesPrePartition, taskImportStrategy == CopyFromS3); err != nil {
		// if import strategy is CopyFromS3, and upload buffer to s3 failed, try to use InsertOnConflict
		if strings.Contains(err.Error(), "Upload buffer to s3 failed") {
			if taskImportStrategy == CopyFromS3 {
				Debug("%v, fallback to InsertOnConflict", err)
				taskImportStrategy = InsertOnConflict
			}
		} else {
			return err
		}
	}

	// create task and send to task queue
	task := NewBufferTask(currentBuffer, deletedRecords, deletedGroupRecords, versionMap, taskImportStrategy)
	p.bufferTaskQueue <- task
	p.lastFlushTime = time.Now()

	return nil
}

// insert threadv2 for buffer
func (p *BulkProcessor) InsertThreadV2() {
	defer p.bufferThreadWg.Done()

	log.Printf("InsertThreadV2 started")

	var localRoutingInited = false
	var localRoutingHashSet map[string]struct{}

	for {
		select {
		case <-p.ctx.Done():
			log.Println("InsertThreadV2 context canceled, exiting...")
			return
		case <-p.routingQueueV2:
			p.routingMutex.Lock()
			localRoutingHashSet = p.routingHashSet
			localRoutingInited = true
			p.routingMutex.Unlock()
		case record := <-p.recordQueueV2:
			values := record.Values
			operation := record.Tag

			recordIndex := RecordIndex{
				fileID:    record.FileID,
				routingID: record.RoutingID,
			}

			if p.feedFieldIndex >= 0 && operation == OperationInsert {
				index := p.feedFieldIndex
				p.feedbackKeysMutex.Lock()
				// Check if feedback column value already exists in the map
				if _, exists := p.feedbackKeys[values[index]]; !exists {
					// Add the feedback column value to the map
					p.feedbackKeys[values[index]] = true
				}
				p.feedbackKeysMutex.Unlock()
			}

			if p.pkColumnsIndex != nil && operation == OperationInsert {
				record.PKValues = make([]string, len(p.pkColumnsIndex))
				for i, index := range p.pkColumnsIndex {
					record.PKValues[i] = values[index]
				}
			}

			toAuxFile := false
			if p.routingColIndex >= 0 {
				if !localRoutingInited {
					p.routingMutex.Lock()
					localRoutingHashSet = p.routingHashSet
					localRoutingInited = true
					p.routingMutex.Unlock()
				}
				if _, exists := localRoutingHashSet[record.RoutingID]; exists {
					toAuxFile = true
				}
			}

			p.bufferManager.bufferOperationsMutex.Lock()

			currentBuffer := p.bufferManager.GetCurrentBuffer(toAuxFile)
			if currentBuffer == nil || !p.bufferManager.IsActive(currentBuffer.ID) {
				currentBuffer = p.bufferManager.NewBuffer(p.config.LocalFilePrefix, p.config.BufferMaxRecords, toAuxFile)
				Debug("New buffer created: %s, max records: %d", currentBuffer.ID, p.config.BufferMaxRecords)
				p.bufferManager.SetCurrentBuffer(currentBuffer, toAuxFile)

				ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
				defer cancel()

				targetTable := p.config.PostgreSQL.Table
				if toAuxFile {
					targetTable = p.GetAuxTableName()
				}
				pgTable := fmt.Sprintf("%s.%s", p.config.PostgreSQL.Schema, targetTable)

				if err := p.pgClient.InsertDeltaCheckpoint(ctx, p.processId, pgTable, currentBuffer.LocalFilePath); err != nil {
					Debug("Failed to insert delta checkpoint with new file: %s, %v", currentBuffer.LocalFilePath, err)
				}
			}

			// check version
			if p.versionColIndex >= 0 && operation == OperationInsert {
				record.Version = values[p.versionColIndex]

				if version, exsit := currentBuffer.MaxVersionMap[recordIndex]; exsit && version > record.Version {
					p.bufferManager.bufferOperationsMutex.Unlock()
					atomic.AddInt32(&p.recordsNum, -1)
					continue
				}
				currentBuffer.MaxVersionMap[recordIndex] = record.Version
			}

			currentBuffer.AddRecord(record)
			atomic.AddInt32(&p.recordsNum, -1)

			if currentBuffer.IsFull() && p.bufferManager.IsActive(currentBuffer.ID) {
				// deactivate current buffer, create new buffer
				p.bufferManager.SetBufferStatus(currentBuffer.ID, BufferStatusFrozen)
				p.bufferManager.SetCurrentBuffer(nil, toAuxFile)
				p.bufferManager.bufferOperationsMutex.Unlock()

				if err := p.SaveBufferToFileAndGenerateTask(currentBuffer, toAuxFile); err != nil {
					p.bufferManager.SetBufferStatus(currentBuffer.ID, BufferStatusFlushError)
					feedbackKeysArray := p.getFeedbackValues()
					feedbackKeysString := fmt.Sprintf("failed %s is [%s].", p.config.FeedbackColumn, strings.Join(feedbackKeysArray, ","))

					if p.config.ImportErrorCallback != nil {
						log.Printf("save file %s failed before callback: %s", currentBuffer.LocalFilePath, feedbackKeysString)
						p.config.ImportErrorCallback(p.config.FeedbackColumn, feedbackKeysArray, err, p.config.CallbackResource)
					} else {
						log.Printf("save file %s failed with no callback: %s", currentBuffer.LocalFilePath, feedbackKeysString)
					}
					continue
				}
				p.bufferManager.SetBufferStatus(currentBuffer.ID, BufferStatusFlushed)
			} else {
				p.bufferManager.bufferOperationsMutex.Unlock()
			}
		}
	}
}

func (p *BulkProcessor) ImporterThreadV2() {
	defer p.bufferThreadWg.Done()

	log.Println("BufferTask thread started")

	for {
		select {
		case <-p.ctx.Done():
			log.Println("BufferTask thread context canceled, exiting...")
			return
		case task := <-p.bufferTaskQueue:

			Debug("Begin to import task: %s, records: %d", task.TaskId, task.RecordCount)

			feedbackKeysArray := p.getFeedbackValues()

			if p.config.MaxConcurrentWorkers > 1 {
				for {
					currentActive := atomic.LoadInt32(&p.activeWorkers)
					if currentActive < int32(p.config.MaxConcurrentWorkers) {
						break
					}
					log.Printf("Waiting for available worker slot, current active: %d, max: %d, queue len: %d",
						currentActive, p.config.MaxConcurrentWorkers, len(p.bufferTaskQueue))
					time.Sleep(500 * time.Millisecond)
				}

				p.workerWg.Add(1)
				workerID := int(atomic.AddInt32(&p.activeWorkers, 1))

				go func(t *BufferTask, wID int) {
					defer p.workerWg.Done()
					defer atomic.AddInt32(&p.activeWorkers, -1)

					log.Printf("Parallel Worker %d started processing task: %s (records: %d)", wID, t.TaskId, t.RecordCount)
					startTime := time.Now()

					p.processBufferTask(t, wID, feedbackKeysArray)

					duration := time.Since(startTime)
					Log("Parallel Worker %d finished import: strategy is %d, processing task: %s, duration: %v", wID, t.ImportStrategy, t.TaskId, duration)
				}(task, workerID)
			} else {
				startTime := time.Now()
				p.processBufferTask(task, -1, feedbackKeysArray)
				Log("Single Worker finished import: strategy is %d, processing task: %s, records: %d, duration: %v", task.ImportStrategy, task.TaskId, task.RecordCount, time.Since(startTime))
			}
		}
	}
}

// parallel process buffer task
func (p *BulkProcessor) processBufferTask(task *BufferTask, workerID int, feedbackKeysArray []string) {

	isFailed := true
	maxLoopNum := p.config.ImportTimeout / p.config.ImportErrorSleepTime
	err := errors.New("Buffer Task timeout")

	for i := 0; i < maxLoopNum; i++ {
		if err := p.processBufferTaskWithTransaction(task, p.config.TaskTimeout); err != nil {

			Warning("Server is busy, will retry to process buffer task %s after %d seconds, error: %v",
				task.TaskId, p.config.ImportErrorSleepTime, err)

			// Update checkpoint with all error file
			ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
			if err2 := p.pgClient.UpdateDeltaCheckpointStatus(ctx, p.processId, []string{task.LocalFile}, CheckpointStatusFailed, -1, err.Error()); err2 != nil {
				Debug("Worker %d failed to update checkpoint for error file: %v\n", workerID, err2)
			}
			cancel()

			// all the errors without parsing error are not expected, we will retry, parsing error just call
			// the callback and continue to next batch
			shouldRetry := true
			for _, skipError := range p.config.SkipServerErrorInfos {
				if strings.Contains(err.Error(), skipError) {
					shouldRetry = false
					break
				}
			}

			if shouldRetry {
				randomOffset := rand.Intn(9) - 4 // 生成 -4 到 4 的随机数
				sleepTime := p.config.ImportErrorSleepTime + randomOffset
				if sleepTime < 0 {
					sleepTime = 1
				}
				time.Sleep(time.Duration(sleepTime) * time.Second)
				continue
			}

			feedbackKeysString := fmt.Sprintf("failed %s is [%s].", p.config.FeedbackColumn, strings.Join(feedbackKeysArray, ","))

			if p.config.ImportErrorCallback != nil {
				Debug("Worker %d task %s failed before callback: %s",
					workerID, task.TaskId, feedbackKeysString)
				p.config.ImportErrorCallback(p.config.FeedbackColumn, feedbackKeysArray, err, p.config.CallbackResource)
			} else {
				Debug("Worker %d task %s failed with no callback: %s",
					workerID, task.TaskId, feedbackKeysString)
			}

			isFailed = true
			break
		} else {
			isFailed = false
			break
		}
	}

	if isFailed {
		p.bufferManager.SetBufferStatus(task.TaskId, BufferStatusImportError)
		feedbackKeysString := fmt.Sprintf("failed %s is [%s].", p.config.FeedbackColumn, strings.Join(feedbackKeysArray, ","))
		Error("Worker %d import task %s failed: %s after retry %d times", workerID, task.TaskId, feedbackKeysString, maxLoopNum)
		if p.config.ImportErrorCallback != nil {
			p.config.ImportErrorCallback(p.config.FeedbackColumn, feedbackKeysArray, err, p.config.CallbackResource)
		}
		return
	}

	// remove local file and delta checkpoint
	if task.LocalFile != "" {
		if err := CleanupLocalFile(task.LocalFile); err != nil {
			Error("Worker %d failed to remove temporary file %s: %v",
				workerID, task.LocalFile, err)
		}

		// Update checkpoint with all imported file
		ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
		if err := p.pgClient.UpdateDeltaCheckpointStatus(ctx, p.processId, []string{task.LocalFile}, CheckpointStatusCompleted, 0, ""); err != nil {
			Debug("Worker %d failed to update checkpoint for imported file: %v\n", workerID, err)
		}
		cancel()
	}

	// success, set buffer status to imported
	p.bufferManager.SetBufferStatus(task.TaskId, BufferStatusImported)

	// Update global max offset after successful import
	if task.MaxOffset > 0 {
		p.UpdateMaxOffset(task.MaxOffset)
	}
}

// processBufferTaskWithTransaction process buffer task with transaction, include delete and import
func (p *BulkProcessor) processBufferTaskWithTransaction(task *BufferTask, timeout int) error {

	deleteBeforeInsert := p.config.DeleteBeforeInsert

	if task.RecordCount <= 0 && len(task.DeletedRecords) == 0 && len(task.DeletedGroupRecords) == 0 {
		Debug("task %s has no records, skip processing", task.TaskId)
		return nil
	}

	// 300 seconds is the max timeout for the transaction
	ctx, cancel := context.WithTimeout(context.Background(), time.Duration(timeout)*time.Second)
	defer cancel()

	conn, err := p.pgClient.pool.Acquire(ctx)
	if err != nil {
		return fmt.Errorf("failed to acquire connection: %w", err)
	}
	defer conn.Release()

	isAuxFile := strings.Contains(task.LocalFile, BufferPrefixAux)
	targetTable := p.config.PostgreSQL.Table
	if isAuxFile {
		targetTable += auxTableSuffix
	}

	updateOnConflict := p.config.UpdateOnConflict
	if deleteBeforeInsert && len(task.FileVersionMap) > 0 {
		updateOnConflict = false
	}

	tx, err := conn.Begin(ctx)
	if err != nil {
		return fmt.Errorf("failed to begin transaction: %w", err)
	}

	success := false
	defer func() {
		if !success {
			if rollbackErr := tx.Rollback(ctx); rollbackErr != nil {
				Error("task %s failed to rollback transaction: %v", task.TaskId, rollbackErr)
			}
			// detach the connection from the pool and close it manually,
			// fix the issue where a segment restart would cause the link to fail to be released
			conn := conn.Hijack()
			conn.Close(ctx)
		}
	}()

	// 1. delete records first
	for _, deletedRecord := range task.DeletedRecords {
		deleteSQL := `SELECT relyt_sys.delete_tables_with_condition(
							$1,  -- schema_name
							$2,  -- main_table
							$3,  -- file_id
							$4,  -- routing_id
							$5   -- have_aux_table
						)`

		// log.Printf("Executing delete SQL in transaction: relyt_sys.delete_tables_with_condition('%s', '%s', '%s', '%s', %t)",
		// 	p.config.PostgreSQL.Schema, p.config.PostgreSQL.Table, deletedRecord.fileID, deletedRecord.routingID, p.hasRoutingTable)

		_, err := tx.Exec(ctx, deleteSQL,
			p.config.PostgreSQL.Schema,
			p.config.PostgreSQL.Table,
			deletedRecord.fileID,
			deletedRecord.routingID,
			p.hasRoutingTable,
		)
		if err != nil {
			return fmt.Errorf("failed to execute delete SQL for %s:%s: %w", deletedRecord.fileID, deletedRecord.routingID, err)
		}
	}

	// 2. delete outdated files
	if len(task.FileVersionMap) > 0 && deleteBeforeInsert {
		if err := p.pgClient.DeleteOutdatedFiles(ctx, tx, targetTable, task.FileVersionMap); err != nil {
			return fmt.Errorf("failed to delete outdated files: %w", err)
		}
	}

	// 3. import file
	if task.LocalFile != "" && task.RecordCount > 0 {
		if task.ImportStrategy == InsertOnConflict {
			if err := p.pgClient.InsertIntoOnConflictFromLocal(ctx, tx, GetLocalFileFullPath(task.LocalFile), targetTable,
				GetColumnNames(p.fields), updateOnConflict, p.config.InsertIntoBatchSize); err != nil {
				return fmt.Errorf("INSERT INTO failed: %w", err)
			}
		} else if task.ImportStrategy == CopyFromLocal {
			if err := p.pgClient.CopyFromLocalOnConflict(ctx, tx, GetLocalFileFullPath(task.LocalFile), targetTable, GetColumnNames(p.fields), updateOnConflict); err != nil {
				return fmt.Errorf("COPY FROM LOCAL failed: %w", err)
			}
		} else if task.ImportStrategy == CopyFromS3 {
			s3Config, err := p.pgClient.GetLoadConfigFromDB(ctx, &p.config)
			if err != nil {
				return fmt.Errorf("failed to get S3 configuration: %w", err)
			}

			if err := p.pgClient.CopyFromS3OnConflict(ctx, tx, p.s3Client.GetS3URL(task.S3File), targetTable, GetColumnNames(p.fields), updateOnConflict, *s3Config); err != nil {
				log.Printf("COPY FROM S3 failed for task %s: %v, falling back to INSERT ON CONFLICT", task.TaskId, err)
				task.ImportStrategy = InsertOnConflict
				return fmt.Errorf("COPY FROM S3 failed: %w", err)
			}
		} else if task.ImportStrategy == InsertFromExtTable {
			s3Config, err := p.pgClient.GetLoadConfigFromDB(ctx, &p.config)
			if err != nil {
				return fmt.Errorf("failed to get S3 configuration: %w", err)
			}

			if err := p.pgClient.InsertIntoFromExternalTable(ctx, tx, p.s3Client.GetS3URL(task.S3File), task.TaskId, targetTable, GetColumnNames(p.fields), updateOnConflict, *s3Config); err != nil {
				task.ImportStrategy = InsertOnConflict
				return fmt.Errorf("INSERT INTO FROM EXTERNAL TABLE failed: %w", err)
			}
		}
	}

	// 4. delete group records
	for _, deletedGroupRecord := range task.DeletedGroupRecords {
		deleteSQL := `SELECT relyt_sys.delete_tables_with_group(
							$1,  -- schema_name
							$2,  -- main_table
							$3,  -- group_id
							$4,  -- routing_id
							$5   -- have_aux_table
						)`

		_, err := tx.Exec(ctx, deleteSQL,
			p.config.PostgreSQL.Schema,
			p.config.PostgreSQL.Table,
			deletedGroupRecord.groupID,
			deletedGroupRecord.routingID,
			p.hasRoutingTable,
		)
		if err != nil {
			return fmt.Errorf("failed to execute delete SQL for %s:%s: %w", deletedGroupRecord.groupID, deletedGroupRecord.routingID, err)
		}
	}

	if err := tx.Commit(ctx); err != nil {
		return fmt.Errorf("task: %s failed to commit transaction: %w", task.TaskId, err)
	}
	success = true

	return nil
}

// processSQLParams process sql params
func processSQLParams(input string, args []interface{}) string {
	if len(args) == 0 {
		return input
	}

	// convert params to string and replace placeholder in condition
	processed := input
	for i, arg := range args {
		// format params according to type
		var valueStr string
		switch v := arg.(type) {
		case string:
			valueStr = fmt.Sprintf("'%s'", strings.ReplaceAll(v, "'", "''"))
		case nil:
			valueStr = "NULL"
		case []interface{}:
			// process array type
			values := make([]string, len(v))
			for j, item := range v {
				switch itemVal := item.(type) {
				case string:
					values[j] = fmt.Sprintf("'%s'", strings.ReplaceAll(itemVal, "'", "''"))
				case nil:
					values[j] = "NULL"
				default:
					values[j] = fmt.Sprintf("%v", itemVal)
				}
			}
			valueStr = strings.Join(values, ",")
		case []string:
			// process string array
			values := make([]string, len(v))
			for j, item := range v {
				values[j] = fmt.Sprintf("'%s'", strings.ReplaceAll(item, "'", "''"))
			}
			valueStr = strings.Join(values, ",")
		case []int64:
			// process int64 array
			values := make([]string, len(v))
			for j, item := range v {
				values[j] = fmt.Sprintf("%d", item)
			}
			valueStr = strings.Join(values, ",")
		case []int32:
			// process int32 array
			values := make([]string, len(v))
			for j, item := range v {
				values[j] = fmt.Sprintf("%d", item)
			}
			valueStr = strings.Join(values, ",")
		case []int:
			// process int array
			values := make([]string, len(v))
			for j, item := range v {
				values[j] = fmt.Sprintf("%d", item)
			}
			valueStr = strings.Join(values, ",")
		case []float64:
			// process float64 array
			values := make([]string, len(v))
			for j, item := range v {
				values[j] = fmt.Sprintf("%f", item)
			}
			valueStr = strings.Join(values, ",")
		case []float32:
			// process float32 array
			values := make([]string, len(v))
			for j, item := range v {
				values[j] = fmt.Sprintf("%f", item)
			}
			valueStr = strings.Join(values, ",")
		case []bool:
			// process bool array
			values := make([]string, len(v))
			for j, item := range v {
				values[j] = fmt.Sprintf("%t", item)
			}
			valueStr = strings.Join(values, ",")
		default:
			valueStr = fmt.Sprintf("%v", v)
		}
		// replace placeholder
		processed = strings.Replace(processed, fmt.Sprintf("$%d", i+1), valueStr, 1)
	}
	return processed
}

func (p *BulkProcessor) CheckTableHasRoutingTable(tableName string) (bool, error) {
	var hasRoutingTable bool
	needCheck := true
	tableName = strings.ToLower(tableName)

	// check cache first, if cache is not expired, return the cached result
	p.routingTableCacheMutex.RLock()
	if ret, exists := p.routingTableCache[tableName]; exists {
		needCheck = time.Since(ret.lastCheckTime) > 5*time.Minute
		hasRoutingTable = ret.hasRoutingTable
	}
	p.routingTableCacheMutex.RUnlock()

	if needCheck {
		var err error
		routingTableName := fmt.Sprintf("%s%s", tableName, routingTableSuffix)
		Log("CheckTableHasRoutingTable: %s, routingTableName: %s", tableName, routingTableName)
		hasRoutingTable, err = p.pgClient.HasRoutingTable(p.ctx, routingTableName)
		if err != nil {
			return false, errors.Wrap(err, "failed to check if routing table exists")
		}

		p.routingTableCacheMutex.Lock()
		p.routingTableCache[tableName] = struct {
			lastCheckTime   time.Time
			hasRoutingTable bool
		}{
			lastCheckTime:   time.Now(),
			hasRoutingTable: hasRoutingTable,
		}
		p.routingTableCacheMutex.Unlock()
	}

	return hasRoutingTable, nil
}

// SearchJsonRowsV2 return pgx.Rows object, let caller control the iteration
// caller need to call rows.Next() and rows.Scan()
func (p *BulkProcessor) SearchJsonRowsV2(options *SearchOptions, args ...interface{}) (pgx.Rows, error) {
	p.mutex.RLock()
	if p.isShutdown {
		p.mutex.RUnlock()
		return nil, ErrProcessorClosed
	}
	p.mutex.RUnlock()

	if options.Table == "" {
		return nil, ErrPostgreSQLTableRequired
	} else {
		options.Table = strings.ToLower(options.Table)
	}

	// process column names
	processedColumns := make([]string, len(options.Columns))
	for i, col := range options.Columns {
		processedColumns[i] = processSQLParams(col, args)
	}

	// process condition params
	processedCondition := processSQLParams(options.Condition, args)

	// process GroupBy params
	processedGroupBy := processSQLParams(options.GroupBy, args)
	processedHaving := processSQLParams(options.Having, args)

	hasRoutingTable, err := p.CheckTableHasRoutingTable(options.Table)
	if err != nil {
		return nil, errors.Wrap(err, "failed to check if routing table exists")
	}

	// prepare params
	params := []interface{}{
		p.config.PostgreSQL.Schema,
		options.Table,
		pq.Array(processedColumns),
		processedCondition,
		options.OrderBy,
		processedGroupBy,
		processedHaving,
		options.Limit,
		options.Offset,
		hasRoutingTable,
	}

	// log.Printf("baseSQL: select * from get_columns_with_condition('%v', '%v', '%v', '%v', '%v', '%v', '%v', '%v', '%v', %t)", params...)

	rows, finalSQL, err := p.pgClient.GetColumnsWithCondition(p.ctx, params...)
	options.FinalSQL = finalSQL
	if err != nil {
		return nil, errors.Wrap(err, "failed to get columns with condition")
	}

	return rows, nil
}

// SearchV2 search data from main table and aux table
func (p *BulkProcessor) SearchV2(options *SearchOptions, args ...interface{}) (*SearchResult, error) {
	// 复用SearchJsonRowsV2的逻辑获取rows
	rows, err := p.SearchJsonRowsV2(options, args...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	// use input column names as result column names
	var allRows [][]interface{}
	var jsonCols []string

	for rows.Next() {
		var resultJSON []byte
		if err := rows.Scan(&resultJSON); err != nil {
			return nil, errors.Wrap(err, "rows.Scan")
		}

		// parse JSONB result
		var rowData map[string]interface{}
		if err := json.Unmarshal(resultJSON, &rowData); err != nil {
			return nil, errors.Wrap(err, "json.Unmarshal")
		}

		// use JSON result column order to build result row
		row := make([]interface{}, len(rowData))
		if jsonCols == nil {
			// extract key order from original JSON string
			decoder := json.NewDecoder(strings.NewReader(string(resultJSON)))
			decoder.UseNumber() // use Number type to keep precision

			// read start object token
			if _, err := decoder.Token(); err != nil {
				return nil, errors.Wrap(err, "read start token")
			}

			// read all keys
			jsonCols = make([]string, 0, len(rowData))
			for decoder.More() {
				token, err := decoder.Token()
				if err != nil {
					return nil, errors.Wrap(err, "read key token")
				}
				key, ok := token.(string)
				if !ok {
					return nil, errors.New("invalid key type")
				}
				jsonCols = append(jsonCols, key)

				// skip value
				if _, err := decoder.Token(); err != nil {
					return nil, errors.Wrap(err, "skip value")
				}
			}
		}

		for i, col := range jsonCols {
			row[i] = rowData[col]
		}

		allRows = append(allRows, row)
	}

	if err := rows.Err(); err != nil {
		return nil, errors.Wrap(err, "rows iteration")
	}

	// if no data, return empty result
	if len(allRows) == 0 {
		return &SearchResult{Columns: []string{}, Rows: [][]interface{}{}}, nil
	}

	return &SearchResult{Columns: jsonCols, Rows: allRows}, nil
}

func (p *BulkProcessor) SearchJsonV2(options *SearchOptions, args ...interface{}) ([]json.RawMessage, error) {
	rows, err := p.SearchJsonRowsV2(options, args...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var jsonResults []json.RawMessage

	for rows.Next() {
		var resultJSON []byte
		if err := rows.Scan(&resultJSON); err != nil {
			return nil, errors.Wrap(err, "rows.Scan")
		}

		jsonResults = append(jsonResults, resultJSON)
	}

	if err := rows.Err(); err != nil {
		return nil, errors.Wrap(err, "rows iteration")
	}

	return jsonResults, nil
}

// SearchJsonRowsWithContextV2 return pgx.Rows object with context to control the query time,
// let caller control the iteration caller need to call rows.Next() and rows.Scan()
// The caller is responsible for managing the context lifecycle
func (p *BulkProcessor) SearchJsonRowsWithContextV2(ctx context.Context, options *SearchOptions, args ...interface{}) (pgx.Rows, error) {
	p.mutex.RLock()
	if p.isShutdown {
		p.mutex.RUnlock()
		return nil, ErrProcessorClosed
	}
	p.mutex.RUnlock()

	if options.Table == "" {
		return nil, ErrPostgreSQLTableRequired
	} else {
		options.Table = strings.ToLower(options.Table)
	}

	// process column names
	processedColumns := make([]string, len(options.Columns))
	for i, col := range options.Columns {
		processedColumns[i] = processSQLParams(col, args)
	}

	// process condition params
	processedCondition := processSQLParams(options.Condition, args)

	// process GroupBy params
	processedGroupBy := processSQLParams(options.GroupBy, args)
	processedHaving := processSQLParams(options.Having, args)

	hasRoutingTable, err := p.CheckTableHasRoutingTable(options.Table)
	if err != nil {
		return nil, errors.Wrap(err, "failed to check if routing table exists")
	}

	// prepare params
	params := []interface{}{
		p.config.PostgreSQL.Schema,
		options.Table,
		pq.Array(processedColumns),
		processedCondition,
		options.OrderBy,
		processedGroupBy,
		processedHaving,
		options.Limit,
		options.Offset,
		hasRoutingTable,
	}

	// log.Printf("baseSQL: select * from get_columns_with_condition('%v', '%v', '%v', '%v', '%v', '%v', '%v', '%v', '%v', %t)", params...)
	start := time.Now()

	rows, finalSQL, err := p.pgClient.GetColumnsWithCondition(ctx, params...)
	options.FinalSQL = finalSQL

	if err != nil {
		if ctx.Err() == context.DeadlineExceeded {
			return nil, errors.New(fmt.Sprintf("search timeout with time cost: %v", time.Since(start)))
		}

		return nil, errors.Wrap(err, "failed to get columns with condition")
	}

	return rows, nil
}
